// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/pkg/grpcx"
	"webook/sms/grpc"
	"webook/sms/ioc"
)

// Injectors from wire.go:

func InitSMSGRPCServer() *grpcx.Server {
	loggerV1 := ioc.InitLogger()
	service := ioc.InitSMSService(loggerV1)
	smsgrpcServer := grpc.NewSMSGRPCServer(service)
	server := ioc.InitGRPCServer(smsgrpcServer, loggerV1)
	return server
}
