db:
  mysql:
    dsn: "root:root@tcp(localhost:13306)/webook_payment?charset=utf8mb4&parseTime=True&loc=Local"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  addr: "localhost:12379"

  grpc:
    server:
      port: 8098
      etcdAddrs:
        - "localhost:12379"