// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/payment/grpc"
	"webook/payment/ioc"
	"webook/payment/repository"
	"webook/payment/repository/dao"
	"webook/payment/web"
)

// Injectors from wire.go:

func InitApp() App {
	wechatConfig := ioc.InitWechatConfig()
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	loggerV1 := ioc.InitLogger()
	client := ioc.InitWechatClient(wechatConfig)
	db := ioc.InitDB(loggerV1)
	paymentDAO := dao.NewPaymentGORMDAO(db)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	saramaClient := ioc.InitKafka()
	producer := ioc.InitProducer(saramaClient)
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, loggerV1, wechatConfig, producer)
	wechatHandler := web.NewWechatHandler(handler, loggerV1, nativePaymentService)
	server := ioc.InitGinServer(wechatHandler)
	wechatServiceServer := grpc.NewWechatServiceServer(nativePaymentService)
	grpcxServer := ioc.InitGRPCServer(wechatServiceServer, loggerV1)
	app := App{
		WebServer:  server,
		GRPCServer: grpcxServer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitEtcd, ioc.InitKafka)
