// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/comment/grpc"
	"webook/comment/ioc"
	"webook/comment/repository"
	"webook/comment/repository/dao"
	"webook/comment/service"
	"webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitCommentGRPCServiceServer() *grpcx.Server {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	commentDao := dao.NewGORMCommentDAO(db)
	commentRepository := repository.NewCommentRepository(commentDao, loggerV1)
	commentService := service.NewCommentService(commentRepository)
	commentServiceServer := grpc.NewCommentServiceServer(commentService)
	server := ioc.InitGRPCServer(commentServiceServer, loggerV1)
	return server
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitEtcd, ioc.InitLogger, ioc.InitDB)
