# pvc => PersistentVolumeClaim
# 开始描述 mysql 的存储结构需要具备什么样的特征
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  这个指的是 mysql 要用的东西
#  还没说 k8s 有什么
  name: webook-mysql-claim
spec:
#  这里的manual 是我们自己写的，只是用来绑定
  storageClassName: manual
#  访问模式，这里主要是控制能不能被多个 pod 读写
  accessModes:
#    被一个 pod 读写
    - ReadWriteOnce
#  究竟需要一些什么资源
  resources:
    requests:
#      需要一个 G 的存储空间
      storage: 1Gi

