# 微服务通用 Docker 配置模板
db:
  mysql:
    dsn: "root:root@tcp(mysql:3306)/webook?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "redis:6379"

kafka:
  addrs:
    - "kafka:9092"

grpc:
  server:
    port: 8090
    etcdAddrs:
      - "etcd:2379"

etcd:
  addr: "etcd:2379"
