// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	events3 "webook/article/events"
	"webook/bff/events"
	"webook/bff/handler"
	"webook/bff/handler/jwt"
	"webook/bff/ioc"
	events2 "webook/interactive/events"
	"webook/interactive/repository"
	"webook/interactive/repository/cache"
	"webook/interactive/repository/dao"
	"webook/interactive/service"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	loggerV1 := ioc.InitLogger()
	v := ioc.InitMiddlewares(cmdable, jwtHandler, loggerV1)
	client := ioc.InitEtcd()
	userServiceClient := ioc.InitUserGRPCClient(client)
	codeServiceClient := ioc.InitCodeGRPCClient(client)
	followServiceClient := ioc.InitFollowGRPCClient(client)
	articleServiceClient := ioc.InitArticleGRPCClientV1(client)
	userHandler := handler.NewUserHandler(userServiceClient, codeServiceClient, followServiceClient, articleServiceClient, cmdable, jwtHandler, loggerV1)
	oauth2ServiceClient := ioc.InitOAuth2GRPCClient(client)
	oAuth2WechatHandler := handler.NewOAuth2WechatHandler(oauth2ServiceClient, userServiceClient, jwtHandler)
	interactiveServiceClient := ioc.InitIntrGRPCClientV2(client)
	rewardServiceClient := ioc.InitRewardGRPCClient(client)
	commentServiceClient := ioc.InitCommentGRPCClient(client)
	tagServiceClient := ioc.InitTagGRPCClient(client)
	historyServiceClient := ioc.InitHistoryGRPCClient(client)
	saramaClient := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(saramaClient)
	notificationProducer := events.NewSaramaNotificationProducer(syncProducer)
	articleHandler := handler.NewArticleHandler(articleServiceClient, loggerV1, interactiveServiceClient, rewardServiceClient, commentServiceClient, userServiceClient, followServiceClient, tagServiceClient, historyServiceClient, notificationProducer)
	followHandler := handler.NewFollowHandler(followServiceClient, userServiceClient, notificationProducer, loggerV1)
	searchServiceClient := ioc.InitSearchGRPCClient(client)
	rankingServiceClient := ioc.InitRankingGRPCClient(client)
	searchHandler := handler.NewSearchHandler(loggerV1, searchServiceClient, userServiceClient, interactiveServiceClient, followServiceClient, rankingServiceClient)
	notificationServiceClient := ioc.InitNotificationGRPCClient(client)
	hub := ioc.InitSSEHub(cmdable, loggerV1)
	notificationHandler := handler.NewNotificationHandler(notificationServiceClient, hub, loggerV1)
	creditServiceClient := ioc.InitCreditGRPCClient(client)
	creditHandler := handler.NewCreditHandler(creditServiceClient, loggerV1)
	tagHandler := handler.NewTagHandler(tagServiceClient, articleServiceClient, loggerV1)
	feedSvcClient := ioc.InitFeedGRPCClient(client)
	feedHandler := handler.NewFeedHandler(feedSvcClient, articleServiceClient, userServiceClient, interactiveServiceClient, commentServiceClient, tagServiceClient, loggerV1)
	rankingHandler := handler.NewRankingHandler(rankingServiceClient, interactiveServiceClient, commentServiceClient, loggerV1)
	imServiceClient := ioc.InitIMGRPCClient(client)
	imHub := ioc.InitIMHub(cmdable, imServiceClient, loggerV1)
	imHandler := handler.NewIMHandler(imServiceClient, userServiceClient, imHub, loggerV1)
	historyHandler := handler.NewHistoryHandler(historyServiceClient, loggerV1)
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler, followHandler, searchHandler, notificationHandler, creditHandler, tagHandler, feedHandler, rankingHandler, imHandler, historyHandler)
	db := ioc.InitDB(loggerV1)
	interactiveDao := dao.NewGORMInteractiveDao(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDao, interactiveCache, loggerV1)
	interactiveReadBatchConsumer := events2.NewInteractiveReadBatchConsumer(saramaClient, loggerV1, interactiveRepository)
	v2 := ioc.NewConsumer(interactiveReadBatchConsumer)
	rlockClient := ioc.InitRLockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingServiceClient, rlockClient, loggerV1)
	cron := ioc.InitJob(loggerV1, rankingJob)
	app := &App{
		Server:    engine,
		Consumers: v2,
		cron:      cron,
	}
	return app
}

// wire.go:

// User 相关依赖
var UserSet = wire.NewSet(handler.NewUserHandler)

// Gorm 文章相关依赖
var GormArticleSet = wire.NewSet(handler.NewArticleHandler)

// FollowSet 关注相关依赖
var FollowSet = wire.NewSet(handler.NewFollowHandler)

var SearchSet = wire.NewSet(handler.NewSearchHandler)

// TagSet 标签相关依赖
var TagSet = wire.NewSet(handler.NewTagHandler, ioc.InitTagGRPCClient)

// FeedSet Feed 相关依赖
var FeedSet = wire.NewSet(handler.NewFeedHandler, ioc.InitFeedGRPCClient)

// RankingSet 排行榜相关依赖
var RankingSet = wire.NewSet(handler.NewRankingHandler)

// NotificationSet 通知相关依赖
var NotificationSet = wire.NewSet(handler.NewNotificationHandler, ioc.InitNotificationGRPCClient, ioc.InitSSEHub)

// NotificationProducerSet 通知事件生产者
var NotificationProducerSet = wire.NewSet(events.NewSaramaNotificationProducer)

var ThirdPartySet = wire.NewSet(ioc.InitRedis, ioc.InitDB, ioc.InitLogger, jwt.NewRedisJWTHandler, ioc.InitEtcd)

var InteractiveSet = wire.NewSet(service.NewInteractiveService, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDao, cache.NewRedisInteractiveCache, events2.NewInteractiveReadBatchConsumer)

var OAuth2Set = wire.NewSet(handler.NewOAuth2WechatHandler)

var KafkaSet = wire.NewSet(ioc.InitKafka, ioc.NewConsumer, ioc.NewSyncProducer, events3.NewKafkaProducer)

var grpcClientSet = wire.NewSet(ioc.InitIntrGRPCClientV2, ioc.InitUserGRPCClient, ioc.InitArticleGRPCClientV1, ioc.InitSMSGRPCClient, ioc.InitCodeGRPCClient, ioc.InitRankingGRPCClient, ioc.InitOAuth2GRPCClient, ioc.InitRewardGRPCClient, ioc.InitFollowGRPCClient, ioc.InitCommentGRPCClient, ioc.InitSearchGRPCClient, ioc.InitCreditGRPCClient)

var CreditSet = wire.NewSet(handler.NewCreditHandler)

// IMSet IM 私信相关依赖
var IMSet = wire.NewSet(handler.NewIMHandler, ioc.InitIMGRPCClient, ioc.InitIMHub)

// HistorySet 浏览历史相关依赖
var HistorySet = wire.NewSet(handler.NewHistoryHandler, ioc.InitHistoryGRPCClient)
