// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/oauth2/grpc"
	"webook/oauth2/ioc"
	"webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitOauth2GRPCServer() *grpcx.Server {
	loggerV1 := ioc.InitLogger()
	service := ioc.InitService(loggerV1)
	oauth2ServiceServer := grpc.NewOauth2ServiceServer(service)
	server := ioc.InitGRPCxServer(oauth2ServiceServer)
	return server
}
