// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/code/grpc"
	"webook/code/ioc"
	"webook/code/repository"
	"webook/code/repository/cache"
	"webook/code/service"
	"webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitCodeGRPCServer() *grpcx.Server {
	cmdable := ioc.InitRedis()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	client := ioc.InitEtcd()
	smsServiceClient := ioc.InitSmsGRPCClient(client)
	loggerV1 := ioc.InitLogger()
	codeService := service.NewCodeService(codeRepository, smsServiceClient, loggerV1)
	codeGRPCServer := grpc.NewCodeGRPCServer(codeService)
	server := ioc.InitGRPCServer(codeGRPCServer, loggerV1)
	return server
}
