db:
  mysql:
    dsn: "root:root@tcp(localhost:13306)/webook_account?charset=utf8mb4&parseTime=True&loc=Local"

etcd:
  addr: "localhost:12379"

grpc:
  server:
    port: 8100
    etcdAddrs:
      - "localhost:12379"