grpc:
  server:
    port: 8096
    etcdAddrs:
      - "localhost:12379"

wechatConf:
  appId: "xxxx"
  appSecret: "xxxx"

prometheus:
  nameSpace: "emoji"
  subsystem: "webook"
  instanceId: ""
  name: "wechat_resp_time"