// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/im/grpc"
	"webook/im/ioc"
	"webook/im/repository"
	"webook/im/repository/cache"
	"webook/im/repository/dao"
	"webook/im/service"
)

// Injectors from wire.go:

func InitApp() *App {
	database := ioc.InitMongo()
	messageDAO := dao.NewMessageDAO(database)
	messageRepository := repository.NewMessageRepository(messageDAO)
	conversationDAO := dao.NewConversationDAO(database)
	cmdable := ioc.InitRedis()
	imCache := cache.NewRedisIMCache(cmdable)
	conversationRepository := repository.NewConversationRepository(conversationDAO, imCache)
	messageService := service.NewMessageService(messageRepository, conversationRepository)
	conversationService := service.NewConversationService(conversationRepository)
	imServiceServer := grpc.NewIMServiceServer(messageService, conversationService)
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGRPCServer(imServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitMongo, ioc.InitLogger, ioc.InitRedis)

var daoSet = wire.NewSet(dao.NewMessageDAO, dao.NewConversationDAO)

var cacheSet = wire.NewSet(cache.NewRedisIMCache)

var repoSet = wire.NewSet(repository.NewMessageRepository, repository.NewConversationRepository)

var serviceSet = wire.NewSet(service.NewMessageService, service.NewConversationService)

var serverSet = wire.NewSet(grpc.NewIMServiceServer, ioc.InitGRPCServer)
