// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	domain "webook/credit/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockCreditService is a mock of CreditService interface.
type MockCreditService struct {
	ctrl     *gomock.Controller
	recorder *MockCreditServiceMockRecorder
}

// MockCreditServiceMockRecorder is the mock recorder for MockCreditService.
type MockCreditServiceMockRecorder struct {
	mock *MockCreditService
}

// NewMockCreditService creates a new mock instance.
func NewMockCreditService(ctrl *gomock.Controller) *MockCreditService {
	mock := &MockCreditService{ctrl: ctrl}
	mock.recorder = &MockCreditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditService) EXPECT() *MockCreditServiceMockRecorder {
	return m.recorder
}

// DeductCredit mocks base method.
func (m *MockCreditService) DeductCredit(ctx context.Context, uid, amount int64, biz, bizId, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductCredit", ctx, uid, amount, biz, bizId, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeductCredit indicates an expected call of DeductCredit.
func (mr *MockCreditServiceMockRecorder) DeductCredit(ctx, uid, amount, biz, bizId, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductCredit", reflect.TypeOf((*MockCreditService)(nil).DeductCredit), ctx, uid, amount, biz, bizId, description)
}

// EarnCredit mocks base method.
func (m *MockCreditService) EarnCredit(ctx context.Context, uid int64, biz string, bizId int64) (int64, int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EarnCredit", ctx, uid, biz, bizId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// EarnCredit indicates an expected call of EarnCredit.
func (mr *MockCreditServiceMockRecorder) EarnCredit(ctx, uid, biz, bizId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EarnCredit", reflect.TypeOf((*MockCreditService)(nil).EarnCredit), ctx, uid, biz, bizId)
}

// GetBalance mocks base method.
func (m *MockCreditService) GetBalance(ctx context.Context, uid int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockCreditServiceMockRecorder) GetBalance(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockCreditService)(nil).GetBalance), ctx, uid)
}

// GetCreditReward mocks base method.
func (m *MockCreditService) GetCreditReward(ctx context.Context, rewardId, uid int64) (domain.CreditReward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreditReward", ctx, rewardId, uid)
	ret0, _ := ret[0].(domain.CreditReward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreditReward indicates an expected call of GetCreditReward.
func (mr *MockCreditServiceMockRecorder) GetCreditReward(ctx, rewardId, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreditReward", reflect.TypeOf((*MockCreditService)(nil).GetCreditReward), ctx, rewardId, uid)
}

// GetDailyStatus mocks base method.
func (m *MockCreditService) GetDailyStatus(ctx context.Context, uid int64, biz string) ([]domain.DailyStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyStatus", ctx, uid, biz)
	ret0, _ := ret[0].([]domain.DailyStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyStatus indicates an expected call of GetDailyStatus.
func (mr *MockCreditServiceMockRecorder) GetDailyStatus(ctx, uid, biz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyStatus", reflect.TypeOf((*MockCreditService)(nil).GetDailyStatus), ctx, uid, biz)
}

// GetFlows mocks base method.
func (m *MockCreditService) GetFlows(ctx context.Context, uid int64, offset, limit int) ([]domain.CreditFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlows", ctx, uid, offset, limit)
	ret0, _ := ret[0].([]domain.CreditFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlows indicates an expected call of GetFlows.
func (mr *MockCreditServiceMockRecorder) GetFlows(ctx, uid, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlows", reflect.TypeOf((*MockCreditService)(nil).GetFlows), ctx, uid, offset, limit)
}

// RewardCredit mocks base method.
func (m *MockCreditService) RewardCredit(ctx context.Context, uid, targetUid int64, biz string, bizId, amt int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RewardCredit", ctx, uid, targetUid, biz, bizId, amt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RewardCredit indicates an expected call of RewardCredit.
func (mr *MockCreditServiceMockRecorder) RewardCredit(ctx, uid, targetUid, biz, bizId, amt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RewardCredit", reflect.TypeOf((*MockCreditService)(nil).RewardCredit), ctx, uid, targetUid, biz, bizId, amt)
}

// Transfer mocks base method.
func (m *MockCreditService) Transfer(ctx context.Context, fromUid, toUid, amount int64, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromUid, toUid, amount, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockCreditServiceMockRecorder) Transfer(ctx, fromUid, toUid, amount, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockCreditService)(nil).Transfer), ctx, fromUid, toUid, amount, description)
}
