// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/history/grpc"
	"webook/history/ioc"
	"webook/history/repository"
	"webook/history/repository/dao"
	"webook/history/service"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	historyDAO := dao.NewGORMHistoryDAO(db)
	historyRepository := repository.NewHistoryRepository(historyDAO)
	historyService := service.NewHistoryService(historyRepository)
	historyServiceServer := grpc.NewHistoryServiceServer(historyService)
	server := ioc.InitGRPCServer(historyServiceServer, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger)

var historySet = wire.NewSet(grpc.NewHistoryServiceServer, service.NewHistoryService, repository.NewHistoryRepository, dao.NewGORMHistoryDAO)
