// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/cronjob/grpc"
	"webook/cronjob/ioc"
	"webook/cronjob/repository"
	"webook/cronjob/repository/dao"
	"webook/cronjob/service"
	"webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitCronJobGRPCServer() *grpcx.Server {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	jobDao := dao.NewGORMJobDAO(db)
	jobRepository := repository.NewPreemptCronJobRepository(jobDao)
	jobService := service.NewCronJobService(jobRepository, loggerV1)
	cronJobServiceServer := grpc.NewCronJobServiceServer(jobService)
	server := ioc.InitGRPCxServer(cronJobServiceServer)
	return server
}
