// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"webook/article/events"
	repository2 "webook/article/repository"
	cache2 "webook/article/repository/cache"
	"webook/article/repository/dao"
	service2 "webook/article/service"
	repository3 "webook/interactive/repository"
	cache3 "webook/interactive/repository/cache"
	dao2 "webook/interactive/repository/dao"
	service3 "webook/interactive/service"
	"webook/internal/handler"
	"webook/internal/handler/jwt"
	"webook/internal/ioc"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/service"
	repository4 "webook/user/repository"
	cache4 "webook/user/repository/cache"
	dao3 "webook/user/repository/dao"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	jwtHandler := jwt.NewRedisJWTHandler(cmdable)
	loggerV1 := InitLog()
	v := ioc.InitMiddlewares(cmdable, jwtHandler, loggerV1)
	userServiceClient := InitUserGRPCClient()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := handler.NewUserHandler(userServiceClient, codeService, cmdable, jwtHandler, loggerV1)
	wechatService := InitWechatService(loggerV1)
	oAuth2WechatHandler := handler.NewOAuth2WechatHandler(wechatService, userServiceClient, jwtHandler)
	db := InitDB()
	articleDao := dao.NewGormArticleDao(db)
	articleCache := cache2.NewRedisArticleCache(cmdable)
	articleRepository := repository2.NewArticleRepository(articleDao, articleCache, loggerV1)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := events.NewKafkaProducer(syncProducer)
	articleService := service2.NewArticleService(articleRepository, loggerV1, producer)
	interactiveDao := dao2.NewGORMInteractiveDao(db)
	interactiveCache := cache3.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository3.NewCachedInteractiveRepository(interactiveDao, interactiveCache, loggerV1)
	interactiveService := service3.NewInteractiveService(interactiveRepository)
	interactiveServiceClient := InitIntrGRPCClient(interactiveService)
	articleHandler := handler.NewArticleHandler(articleService, loggerV1, interactiveServiceClient)
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

func InitArticleHandler(d dao.ArticleDao) *handler.ArticleHandler {
	cmdable := InitRedis()
	articleCache := cache2.NewRedisArticleCache(cmdable)
	loggerV1 := InitLog()
	articleRepository := repository2.NewArticleRepository(d, articleCache, loggerV1)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := events.NewKafkaProducer(syncProducer)
	articleService := service2.NewArticleService(articleRepository, loggerV1, producer)
	db := InitDB()
	interactiveDao := dao2.NewGORMInteractiveDao(db)
	interactiveCache := cache3.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository3.NewCachedInteractiveRepository(interactiveDao, interactiveCache, loggerV1)
	interactiveService := service3.NewInteractiveService(interactiveRepository)
	interactiveServiceClient := InitIntrGRPCClient(interactiveService)
	articleHandler := handler.NewArticleHandler(articleService, loggerV1, interactiveServiceClient)
	return articleHandler
}

// wire.go:

var thirdPartySet = wire.NewSet(
	NewSyncProducer,
	InitKafka,
	InitDB,
	InitRedis,
	InitLog,
)

var userSvcProvider = wire.NewSet(dao3.NewUserDao, cache4.NewUserCache, repository4.NewCachedUserRepository, InitUserGRPCClient, handler.NewUserHandler)

var articleSet = wire.NewSet(handler.NewArticleHandler, service2.NewArticleService, repository2.NewArticleRepository, dao.NewGormArticleDao, cache2.NewRedisArticleCache, events.NewKafkaProducer)

var interactiveSet = wire.NewSet(service3.NewInteractiveService, repository3.NewCachedInteractiveRepository, dao2.NewGORMInteractiveDao, cache3.NewRedisInteractiveCache)
