// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/pkg/grpcx"
	"webook/ranking/grpc"
	"webook/ranking/ioc"
	"webook/ranking/repository"
	"webook/ranking/repository/cache"
	"webook/ranking/service"
)

// Injectors from wire.go:

func InitRankingGRPCServer() *grpcx.Server {
	articleServiceClient := ioc.InitArticleGRPCClient()
	interactiveServiceClient := ioc.InitIntrGRPCClient()
	cmdable := ioc.InitRedis()
	rankingRedisCache := cache.NewRankingRedisCache(cmdable)
	rankingLocalCache := cache.NewRankingLocalCache()
	rankingRepository := repository.NewCachedRankingRepository(rankingRedisCache, rankingLocalCache)
	rankingService := service.NewBatchRankingService(articleServiceClient, interactiveServiceClient, rankingRepository)
	rankingServiceServer := grpc.NewRankingServiceServer(rankingService)
	server := ioc.InitGRPCServer(rankingServiceServer)
	return server
}

// wire.go:

var grpcClientSet = wire.NewSet(ioc.InitArticleGRPCClient, ioc.InitIntrGRPCClient)
