// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/account/grpc"
	"webook/account/ioc"
	"webook/account/repository"
	"webook/account/repository/dao"
	"webook/account/service"
	"webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitGRPCServiceServer() *grpcx.Server {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	accountDAO := dao.NewAccountGORMDAO(db)
	accountRepository := repository.NewAccountRepository(accountDAO)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	server := ioc.InitGRPCServer(accountServiceServer, loggerV1)
	return server
}
