db:
  mysql:
    dsn: "root:root@tcp(localhost:13306)/webook?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"


grpc:
  server:
    addr: "127.0.0.1:8090"