db:
  mysql:
    dsn: "root:root@tcp(localhost:13306)/webook?charset=utf8mb4&parseTime=True&loc=Local"
  mongo:
    url: "mongodb://root:example@localhost:27017/"

redis:
  addr: "localhost:6379"

web:
  logreq: false

oss:
  bucket: "webook-1258698140"
  region: "ap-nanjing"
  endpoint: "https://webook-1258698140.cos.ap-nanjing.myqcloud.com"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  client:
    intr:
      addr: "127.0.0.1:8090"
      secure: false
      threshold: 70
    user:
      addr: "127.0.0.1:8091"
      secure: false
    article:
      addr: "127.0.0.1:8092"
      secure: false
    sms:
      addr: "127.0.0.1:8093"
      secure: false
    code:
      addr: "127.0.0.1:8094"
      secure: false
    ranking:
      addr: "127.0.0.1:8095"
      secure: false
    oauth2:
      addr: "127.0.0.1:8096"
      secure: false
