db:
  mysql:
    dsn: "root:root@tcp(localhost:13306)/webook?charset=utf8mb4&parseTime=True&loc=Local"
  mongo:
    url: "mongodb://root:example@localhost:27017/"

redis:
  addr: "localhost:6379"

web:
  logreq: false

oss:
  bucket: "webook-1258698140"
  region: "ap-nanjing"
  endpoint: "https://webook-1258698140.cos.ap-nanjing.myqcloud.com"

kafka:
  addrs:
    - "localhost:9094"