db:
  mysql:
    dsn: "root:root@tcp(localhost:13306)/webook_follow?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"

etcd:
  addr: "localhost:12379"

grpc:
  server:
    port: 8102
    etcdAddrs:
      - "localhost:12379"