// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/notification/channel"
	"webook/notification/events"
	"webook/notification/grpc"
	"webook/notification/ioc"
	"webook/notification/repository"
	"webook/notification/repository/cache"
	"webook/notification/repository/dao"
	"webook/notification/service"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	notificationDAO := dao.NewGORMNotificationDAO(db)
	cmdable := ioc.InitRedis()
	notificationCache := cache.NewRedisNotificationCache(cmdable)
	notificationRepository := repository.NewCachedNotificationRepository(notificationDAO, notificationCache, loggerV1)
	inAppSender := channel.NewInAppSender(notificationRepository)
	smsProvider := ioc.InitSMSProvider()
	templateDAO := dao.NewGORMTemplateDAO(db)
	templateCache := cache.NewRedisTemplateCache(cmdable)
	templateRepository := repository.NewCachedTemplateRepository(templateDAO, templateCache, loggerV1)
	smsSender := channel.NewSMSSender(smsProvider, templateRepository)
	emailSender := channel.NewEmailSender()
	v := ioc.InitChannelSenders(inAppSender, smsSender, emailSender)
	transactionDAO := dao.NewGORMTransactionDAO(db)
	transactionRepository := repository.NewTransactionRepository(transactionDAO)
	templateService := service.NewTemplateService(templateRepository)
	notificationService := service.NewNotificationService(v, notificationRepository, transactionRepository, templateService)
	notificationServiceServer := grpc.NewNotificationServiceServer(notificationService, templateService)
	server := ioc.InitGRPCServer(notificationServiceServer, loggerV1)
	client := ioc.InitKafka()
	notificationEventConsumer := events.NewNotificationEventConsumer(client, notificationService, loggerV1)
	likeEventConsumer := events.NewLikeEventConsumer(client, notificationService, loggerV1)
	collectEventConsumer := events.NewCollectEventConsumer(client, notificationService, loggerV1)
	commentEventConsumer := events.NewCommentEventConsumer(client, notificationService, loggerV1)
	followEventConsumer := events.NewFollowEventConsumer(client, notificationService, loggerV1)
	v2 := ioc.NewConsumers(notificationEventConsumer, likeEventConsumer, collectEventConsumer, commentEventConsumer, followEventConsumer)
	clientv3Client := ioc.InitETCDClient()
	checkBackScheduler := ioc.InitCheckBackScheduler(transactionRepository, notificationService, clientv3Client, loggerV1)
	app := &App{
		server:    server,
		consumers: v2,
		scheduler: checkBackScheduler,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka, ioc.InitSyncProducer, ioc.InitETCDClient)

var templateSet = wire.NewSet(service.NewTemplateService, repository.NewCachedTemplateRepository, dao.NewGORMTemplateDAO, cache.NewRedisTemplateCache)

var channelSet = wire.NewSet(channel.NewInAppSender, channel.NewSMSSender, channel.NewEmailSender, ioc.InitSMSProvider, ioc.InitChannelSenders)

var notificationSet = wire.NewSet(grpc.NewNotificationServiceServer, service.NewNotificationService, repository.NewCachedNotificationRepository, repository.NewTransactionRepository, dao.NewGORMNotificationDAO, dao.NewGORMTransactionDAO, cache.NewRedisNotificationCache)

var schedulerSet = wire.NewSet(ioc.InitCheckBackScheduler)

var consumerSet = wire.NewSet(events.NewNotificationEventConsumer, events.NewLikeEventConsumer, events.NewCollectEventConsumer, events.NewCommentEventConsumer, events.NewFollowEventConsumer, ioc.NewConsumers)
