// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/follow/grpc"
	"webook/follow/ioc"
	"webook/follow/repository"
	"webook/follow/repository/cache"
	"webook/follow/repository/dao"
	"webook/follow/service"
	"webook/pkg/grpcx"
)

// Injectors from wire.go:

func InitFollowGRPCServer() *grpcx.Server {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	followDao := dao.NewGORMFollowDao(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewCachedFollowRepository(followDao, followCache, loggerV1)
	followService := service.NewFollowService(followRepository)
	followServiceServer := grpc.NewFollowServiceServer(followService)
	server := ioc.InitGRPCServer(followServiceServer, loggerV1)
	return server
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitEtcd)
