// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/pkg/grpcx"
	"webook/reward/grpc"
	"webook/reward/ioc"
	"webook/reward/repository"
	"webook/reward/repository/cache"
	"webook/reward/repository/dao"
	"webook/reward/service"
)

// Injectors from wire.go:

func InitRewardGRPCServer() *grpcx.Server {
	client := ioc.InitEtcd()
	wechatPaymentServiceClient := ioc.InitPaymentGRPCClientV1(client)
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	rewardDAO := dao.NewRewardGORMDAO(db)
	cmdable := ioc.InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	rewardService := service.NewWechatNativeRewardService(wechatPaymentServiceClient, rewardRepository, loggerV1)
	rewardServiceServer := grpc.NewRewardServiceServer(rewardService)
	server := ioc.InitGRPCServer(rewardServiceServer, loggerV1)
	return server
}

// wire.go:

var thirdPartyWireSet = wire.NewSet(ioc.InitDB, ioc.InitEtcd, ioc.InitLogger, ioc.InitRedis)
