redis:
  addr: "localhost:6379"

grpc:
  server:
    port: 8095
    etcdAddrs:
      - "localhost:12379"
  client:
    article:
      secure: false
    interactive:
      secure: false

etcd:
  addr: "localhost:12379"