// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/credit/events"
	"webook/credit/grpc"
	"webook/credit/ioc"
	"webook/credit/repository"
	"webook/credit/repository/cache"
	"webook/credit/repository/dao"
	"webook/credit/service"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	creditDAO := dao.NewCreditGORMDAO(db)
	cmdable := ioc.InitRedis()
	creditCache := cache.NewCreditRedisCache(cmdable)
	creditRepository := repository.NewCreditRepository(creditDAO, creditCache)
	creditService := service.NewCreditService(creditRepository, loggerV1)
	creditServiceServer := grpc.NewCreditServiceServer(creditService)
	server := ioc.InitGRPCServer(creditServiceServer, loggerV1)
	client := ioc.InitEtcd()
	openAPIServiceClient := ioc.InitOpenAPIGRPCClient(client)
	handler := ioc.InitCreditAPIHandler(openAPIServiceClient, creditService, loggerV1)
	epayHandler := ioc.InitEpayHandler(creditRepository, openAPIServiceClient, loggerV1)
	ginxServer := ioc.InitHTTPServer(handler, epayHandler)
	saramaClient := ioc.InitKafka()
	readEventConsumer := events.NewReadEventConsumer(saramaClient, creditService, loggerV1)
	likeEventConsumer := events.NewLikeEventConsumer(saramaClient, creditService, loggerV1)
	collectEventConsumer := events.NewCollectEventConsumer(saramaClient, creditService, loggerV1)
	v := ioc.NewConsumers(readEventConsumer, likeEventConsumer, collectEventConsumer)
	app := &App{
		server:     server,
		httpServer: ginxServer,
		consumers:  v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitEtcd, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka)

var creditSet = wire.NewSet(grpc.NewCreditServiceServer, service.NewCreditService, repository.NewCreditRepository, dao.NewCreditGORMDAO, cache.NewCreditRedisCache)

var openAPISet = wire.NewSet(ioc.InitOpenAPIGRPCClient, ioc.InitCreditAPIHandler, ioc.InitEpayHandler)

var consumerSet = wire.NewSet(events.NewReadEventConsumer, events.NewLikeEventConsumer, events.NewCollectEventConsumer)
