// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"webook/api/proto/gen/payment/v1"
	"webook/reward/repository"
	"webook/reward/repository/cache"
	"webook/reward/repository/dao"
	"webook/reward/service"
)

// Injectors from wire.go:

func InitWechatNativeSvc(client pmtv1.WechatPaymentServiceClient) service.RewardService {
	db := InitDB()
	rewardDAO := dao.NewRewardGORMDAO(db)
	cmdable := InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	loggerV1 := InitLog()
	rewardService := service.NewWechatNativeRewardService(client, rewardRepository, loggerV1)
	return rewardService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitDB, InitLog, InitRedis)
